### ISSUE TITLE
Investigate `io.r2dbc.postgresql.client.ReactorNettyClient` exception

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4997] opened 2023-12-19 10:29 UTC
When performance test with james-gatling,
I got an exception looks below
I tried to decrease users 5000->500, but it still present.
Tracking why and fixing it

```
10:25:47.463 [ERROR] o.a.j.i.p.AbstractMailboxProcessor - Unexpected error during IMAP processing
2023-12-19T10:25:47.463747215Z io.r2dbc.postgresql.client.ReactorNettyClient$RequestQueueException: Cannot exchange messages because the request queue limit is exceeded
2023-12-19T10:25:47.463750862Z 	... 152 common frames omitted
...........
; Cannot exchange messages because the request queue limit is exceeded
2023-12-19T10:25:47.463775870Z 	at org.jooq.impl.Tools.translate(Tools.java:3113)
2023-12-19T10:25:47.463778585Z 	at org.jooq.impl.Tools.translate(Tools.java:3097)
2023-12-19T10:25:47.463781250Z 	at org.jooq.impl.R2DBC$Forwarding.onError(R2DBC.java:245)
2023-12-19T10:25:47.463783975Z 	at reactor.core.publisher.StrictSubscriber.onError(StrictSubscriber.java:106)
2023-12-19T10:25:47.463795157Z 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onError(FluxHandleFuseable.java:229)
2023-12-19T10:25:47.463798002Z 	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:108)
2023-12-19T10:25:47.463800737Z 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:213)
2023-12-19T10:25:47.463803493Z 	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255)
2023-12-19T10:25:47.463806288Z 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onError(FluxHandleFuseable.java:229)
2023-12-19T10:25:47.463809043Z 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onError(FluxFilterFuseable.java:382)
2023-12-19T10:25:47.463811849Z 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
2023-12-19T10:25:47.463814634Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903)
2023-12-19T10:25:47.463817419Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903)
2023-12-19T10:25:47.463820395Z 	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onError(FluxDiscardOnCancel.java:97)
2023-12-19T10:25:47.463823220Z 	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:119)
2023-12-19T10:25:47.463826076Z 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:213)
2023-12-19T10:25:47.463829172Z 	at reactor.core.publisher.FluxCreate$BaseSink.error(FluxCreate.java:479)
2023-12-19T10:25:47.463831897Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:868)
2023-12-19T10:25:47.463834652Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.error(FluxCreate.java:813)
2023-12-19T10:25:47.463837458Z 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:239)
2023-12-19T10:25:47.463840213Z 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:215)
2023-12-19T10:25:47.463853118Z 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.error(FluxCreate.java:191)
2023-12-19T10:25:47.463868688Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.lambda$addConversation$1(ReactorNettyClient.java:752)
2023-12-19T10:25:47.463877895Z 	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:97)
2023-12-19T10:25:47.463886331Z 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68)
2023-12-19T10:25:47.463894417Z 	at io.r2dbc.postgresql.util.FluxDiscardOnCancel.subscribe(FluxDiscardOnCancel.java:49)
2023-12-19T10:25:47.463903925Z 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68)
2023-12-19T10:25:47.463914195Z 	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
2023-12-19T10:25:47.463929975Z 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
2023-12-19T10:25:47.463948110Z 	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
2023-12-19T10:25:47.463962037Z 	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:240)
2023-12-19T10:25:47.463982456Z 	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:357)
2023-12-19T10:25:47.463996923Z 	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
2023-12-19T10:25:47.464009898Z 	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerComplete(FluxConcatMapNoPrefetch.java:274)
2023-12-19T10:25:47.464022723Z 	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onComplete(FluxConcatMap.java:887)
2023-12-19T10:25:47.464049434Z 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2098)
2023-12-19T10:25:47.464072498Z 	at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:163)
2023-12-19T10:25:47.464085894Z 	at reactor.core.publisher.MonoSupplier$MonoSupplierSubscription.request(MonoSupplier.java:148)
2023-12-19T10:25:47.464106774Z 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2067)
2023-12-19T10:25:47.464125490Z 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2331)
2023-12-19T10:25:47.464142282Z 	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338)
2023-12-19T10:25:47.464157271Z 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2067)
2023-12-19T10:25:47.464171649Z 	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:141)
2023-12-19T10:25:47.464184964Z 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2051)
2023-12-19T10:25:47.464199682Z 	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164)
2023-12-19T10:25:47.464223648Z 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
2023-12-19T10:25:47.464237815Z 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
2023-12-19T10:25:47.464250790Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4512)
2023-12-19T10:25:47.464274907Z 	at org.jooq.impl.R2DBC$RowCountSubscriber.onNext(R2DBC.java:309)
2023-12-19T10:25:47.464295386Z 	at org.jooq.impl.R2DBC$RowCountSubscriber.onNext(R2DBC.java:302)
2023-12-19T10:25:47.464314432Z 	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
2023-12-19T10:25:47.464329241Z 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2023-12-19T10:25:47.464347366Z 	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571)
2023-12-19T10:25:47.464366973Z 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164)
2023-12-19T10:25:47.464383124Z 	at reactor.core.publisher.StrictSubscriber.onSubscribe(StrictSubscriber.java:77)
2023-12-19T10:25:47.464397031Z 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92)
2023-12-19T10:25:47.464424193Z 	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
2023-12-19T10:25:47.464441205Z 	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
2023-12-19T10:25:47.464462326Z 	at reactor.core.publisher.Flux.subscribe(Flux.java:8777)
2023-12-19T10:25:47.464492494Z 	at org.jooq.impl.R2DBC$QueryExecutionSubscriber.onNext0(R2DBC.java:446)
2023-12-19T10:25:47.464506280Z 	at org.jooq.impl.R2DBC$ConnectionSubscriber.onNext(R2DBC.java:383)
2023-12-19T10:25:47.464520197Z 	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.lambda$request0$0(R2DBC.java:593)
2023-12-19T10:25:47.464531959Z 	at org.jooq.impl.Internal$1.onNext(Internal.java:442)
2023-12-19T10:25:47.464547890Z 	at org.jooq.impl.Internal$1.onNext(Internal.java:442)
2023-12-19T10:25:47.464561346Z 	at org.jooq.impl.DefaultConnectionFactory.lambda$create$0(DefaultConnectionFactory.java:86)
2023-12-19T10:25:47.464575884Z 	at org.jooq.impl.R2DBC$AbstractSubscription$1.request0(R2DBC.java:153)
2023-12-19T10:25:47.464589319Z 	at org.jooq.impl.ThreadGuard.lambda$run$0(ThreadGuard.java:74)
2023-12-19T10:25:47.464604799Z 	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:87)
2023-12-19T10:25:47.464622403Z 	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:74)
2023-12-19T10:25:47.464639245Z 	at org.jooq.impl.R2DBC$AbstractSubscription.request(R2DBC.java:186)
2023-12-19T10:25:47.464650847Z 	at org.jooq.impl.R2DBC$ConnectionSubscriber.onSubscribe(R2DBC.java:377)
2023-12-19T10:25:47.464684682Z 	at org.jooq.impl.Internal$1.onSubscribe(Internal.java:437)
2023-12-19T10:25:47.464701705Z 	at org.jooq.impl.DefaultConnectionFactory.lambda$create$1(DefaultConnectionFactory.java:85)
2023-12-19T10:25:47.464715291Z 	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.request0(R2DBC.java:590)
2023-12-19T10:25:47.464730009Z 	at org.jooq.impl.ThreadGuard.lambda$run$0(ThreadGuard.java:74)
2023-12-19T10:25:47.464742413Z 	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:87)
2023-12-19T10:25:47.464755348Z 	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:74)
2023-12-19T10:25:47.464765157Z 	at org.jooq.impl.R2DBC$AbstractSubscription.request(R2DBC.java:186)
2023-12-19T10:25:47.464770156Z 	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108)
2023-12-19T10:25:47.464792940Z 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:291)
2023-12-19T10:25:47.464814000Z 	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
2023-12-19T10:25:47.464832205Z 	at org.jooq.impl.AbstractRowCountQuery.subscribe(AbstractRowCountQuery.java:65)
2023-12-19T10:25:47.464846643Z 	at org.jooq.impl.AbstractDelegatingDMLQuery.subscribe(AbstractDelegatingDMLQuery.java:67)
2023-12-19T10:25:47.464859538Z 	at reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:64)
2023-12-19T10:25:47.464879987Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
2023-12-19T10:25:47.464893603Z 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
2023-12-19T10:25:47.464906959Z 	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
2023-12-19T10:25:47.464920515Z 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
2023-12-19T10:25:47.464932818Z 	at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:156)
2023-12-19T10:25:47.464941755Z 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367)
2023-12-19T10:25:47.464952506Z 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241)
2023-12-19T10:25:47.464966603Z 	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
2023-12-19T10:25:47.464980429Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4512)
2023-12-19T10:25:47.464993885Z 	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:205)
2023-12-19T10:25:47.465005387Z 	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
2023-12-19T10:25:47.465018112Z 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:63)
2023-12-19T10:25:47.465032369Z 	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:80)
2023-12-19T10:25:47.465045384Z 	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
2023-12-19T10:25:47.465058349Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4496)
2023-12-19T10:25:47.465069430Z 	at reactor.core.publisher.MonoIgnorePublisher.subscribe(MonoIgnorePublisher.java:57)
2023-12-19T10:25:47.465083126Z 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:264)
2023-12-19T10:25:47.465096191Z 	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
2023-12-19T10:25:47.465109587Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4512)
2023-12-19T10:25:47.465122362Z 	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:205)
2023-12-19T10:25:47.465134625Z 	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
2023-12-19T10:25:47.465148321Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4496)
2023-12-19T10:25:47.465162509Z 	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:202)
2023-12-19T10:25:47.465175684Z 	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
2023-12-19T10:25:47.465183479Z 	at reactor.core.publisher.Mono.subscribe(Mono.java:4496)
2023-12-19T10:25:47.465194450Z 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:430)
2023-12-19T10:25:47.465213787Z 	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:335)
2023-12-19T10:25:47.465230910Z 	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
2023-12-19T10:25:47.465240057Z 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:373)
2023-12-19T10:25:47.465258583Z 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
2023-12-19T10:25:47.465275205Z 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
2023-12-19T10:25:47.465291125Z 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68)
2023-12-19T10:25:47.465301225Z 	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
2023-12-19T10:25:47.465329499Z 	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
2023-12-19T10:25:47.465350639Z 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2023-12-19T10:25:47.465378833Z 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2023-12-19T10:25:47.465395105Z 	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
2023-12-19T10:25:47.465410805Z 	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:177)
2023-12-19T10:25:47.465422848Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
2023-12-19T10:25:47.465433548Z 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
2023-12-19T10:25:47.465450240Z 	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
2023-12-19T10:25:47.465463045Z 	at org.jooq.impl.Internal$1.onNext(Internal.java:442)
2023-12-19T10:25:47.465475248Z 	at org.jooq.impl.R2DBC$Forwarding.onNext(R2DBC.java:238)
2023-12-19T10:25:47.465493393Z 	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
2023-12-19T10:25:47.465509995Z 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
2023-12-19T10:25:47.465525515Z 	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
2023-12-19T10:25:47.465539081Z 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194)
2023-12-19T10:25:47.465552667Z 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
2023-12-19T10:25:47.465565852Z 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2023-12-19T10:25:47.465584788Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
2023-12-19T10:25:47.465609786Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
2023-12-19T10:25:47.465634935Z 	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:91)
2023-12-19T10:25:47.465650174Z 	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
2023-12-19T10:25:47.465658460Z 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
2023-12-19T10:25:47.465672637Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:880)
2023-12-19T10:25:47.465692796Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:805)
2023-12-19T10:25:47.465709508Z 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:163)
2023-12-19T10:25:47.465723174Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:684)
2023-12-19T10:25:47.465751638Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:936)
2023-12-19T10:25:47.465766998Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:810)
2023-12-19T10:25:47.465780734Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:716)
2023-12-19T10:25:47.465796945Z 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
2023-12-19T10:25:47.465812255Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
2023-12-19T10:25:47.465825310Z 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
2023-12-19T10:25:47.465834397Z 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
2023-12-19T10:25:47.465845819Z 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:294)
2023-12-19T10:25:47.465866108Z 	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:403)
2023-12-19T10:25:47.465881778Z 	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:426)
2023-12-19T10:25:47.465896937Z 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
2023-12-19T10:25:47.465912837Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-12-19T10:25:47.465926403Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-19T10:25:47.465939599Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-12-19T10:25:47.465952784Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2023-12-19T10:25:47.465965679Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
2023-12-19T10:25:47.465972812Z 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
2023-12-19T10:25:47.465975558Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
2023-12-19T10:25:47.465977982Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-12-19T10:25:47.465981379Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-19T10:25:47.465983553Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-12-19T10:25:47.465985657Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-12-19T10:25:47.465987851Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-12-19T10:25:47.465989935Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-19T10:25:47.465992109Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-12-19T10:25:47.465994193Z 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
2023-12-19T10:25:47.465996298Z 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
2023-12-19T10:25:47.465998341Z 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
2023-12-19T10:25:47.466000385Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-12-19T10:25:47.466002449Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-12-19T10:25:47.466004493Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-12-19T10:25:47.466006557Z 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Arsnael** [comment] 2023-12-19 10:36
Request queue limit exceeded? Are we trying to push too much to postgres? Or is it the queue on James side that gets full quickly? 

Good catch, might be maybe some fine tuning to do there...

**Comment by quantranhong1999** [comment] 2023-12-19 10:47
Likely we should put less pressure on PG by sending fewer concurrent queries. e.g. `flatMap` to `concatMap`.

**Comment by chibenwa** [comment] 2023-12-20 06:59
Or...

Or we are doing too many requests.

I advocate being able to log and aggregate each request and execution time. And review which requests takes time. And review rewquest counts.

Ideally a tool like glowroot APM. But a tool like slow request log on PG side might already be valuable.

Keep in mind that bounded parallelism and queue size is intended as a defense mechanism. If brought too high, we might actually overload the DB (but we can try the impact of increasing those...

**Comment by vttranlina** [comment] 2024-02-20 11:49
I tried to increase the queue size 
by `jvm.properties` :
`-Dreactor.bufferSize.small=100000`

The staging works well when Gatling tests with 3000 users. (that was impossible in the past, before that the threshold was 100-1500 users/ 1 pod)

________
Gatling result: 
The KO is 0%, but the 99th percent is quiet high

![image](https://github.com/linagora/james-project/assets/81145350/666705b6-58c7-4d97-93d0-d2fffe1dbb25)




___________
The jvm option was found at https://github.com/pgjdbc/r2dbc-postgresql/issues/360#issuecomment-869422327 
postgresql/issues/360#issuecomment-869422327 
(by who got the same issue)

**Comment by vttranlina** [comment] 2024-02-20 12:08
The argument `-Dreactor.bufferSize.small` is generic to the reactor. 
Not sure if it is necessary or not when documenting it in James Postgres.
anw, I created a PR for that, https://github.com/apache/james-project/pull/2030

**Comment by vttranlina** [comment] 2024-02-20 12:10
Or we should have the dedicated property for configuring queue size for only Postgres reactor. (maybe in the PostgresExecutor class, not sure it is possible)

**Comment by chibenwa** [comment] 2024-02-20 19:36
Perf here is still bad.

I do expect connection pooling options from JOOQ. I do not see what reactor stuff have to do with it.

BTW I would expect bad result to be caused by a clumsy "Postgres in K8S" set up. We shall ask for a dedicated managed instance.

**Comment by Arsnael** [comment] 2024-02-21 02:17
> BTW I would expect bad result to be caused by a clumsy "Postgres in K8S" set up. We shall ask for a dedicated managed instance.

@ducnm0711 did get us an access to one FYI. I just could not connect correctly to it. We agreed initially to check that after tet (maybe just a story of whitelist james-postgres or something) but with CNB kicking, didn't have time to look at it yet.

This isn't a priority atm

**Comment by chibenwa** [comment] 2024-02-21 08:49
Ok.

I sent an email yesterday night on this very topic, with @ducnm0711 cced

**Comment by Arsnael** [comment] 2024-03-25 08:57
I didn't notice this anymore when running perf tests after moving to postgres ovh service.

Closing this.

**Closed** 2024-03-25 08:57 UTC
Labels: Postgresql

**Comment by elkin5** [comment] 2024-04-19 03:05
Hello @vttranlina , Could you help me on how to configure the variable? I have the same problem, I have tried to add it as a system variable to the execution of the .jar but it gives me this error : 

```
java -Dreactor.bufferSize.small=10000 -jar app-service.jar
Error: no se ha encontrado o cargado la clase principal .bufferSize.small=10000
Causado por: java.lang.ClassNotFoundException: /bufferSize/small=10000
```
I really appreciate that you can help me. It is a complex issue and there are few alternatives.

**Comment by vttranlina** [comment] 2024-04-19 03:08
> Hello @vttranlina , Could you help me on how to configure the variable? I have the same problem, I have tried to add it as a system variable to the execution of the .jar but it gives me this error :
> 
> ```
> java -Dreactor.bufferSize.small=10000 -jar app-service.jar
> Error: no se ha encontrado o cargado la clase principal .bufferSize.small=10000
> Causado por: java.lang.ClassNotFoundException: /bufferSize/small=10000
> ```
> 
> I really appreciate that you can help me. It is a complex issue and there are few alternatives.

Do you use james? or other project?

`ausado por: java.lang.ClassNotFoundException: /bufferSize/small=10000` It looks like the `app-service` doesn't use reactor library

**Comment by elkin5** [comment] 2024-04-19 03:17
> > Hello @vttranlina , Could you help me on how to configure the variable? I have the same problem, I have tried to add it as a system variable to the execution of the .jar but it gives me this error :
> > ```
> > java -Dreactor.bufferSize.small=10000 -jar app-service.jar
> > Error: no se ha encontrado o cargado la clase principal .bufferSize.small=10000
> > Causado por: java.lang.ClassNotFoundException: /bufferSize/small=10000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I really appreciate that you can help me. It is a complex issue and there are few alternatives.
> 
> Do you use james? or other project?
> 
> `ausado por: java.lang.ClassNotFoundException: /bufferSize/small=10000` It looks like the `app-service` doesn't use reactor library

No, I am using spring webflux, could I apply to this type of projects?

**Comment by quantranhong1999** [comment] 2024-04-19 03:18
> I really appreciate that you can help me. It is a complex issue and there are few alternatives.

Are you using r2dbc?

Recently we have tried a connection pool (instead of a single connection) for our app and the performance is good. The `Cannot exchange messages because the request queue limit is exceeded` seems not to happen anymore.

**Comment by quantranhong1999** [comment] 2024-04-19 03:25
>  No, I am using spring webflux, could I apply to this type of projects?

`When you use Spring’s R2DBC layer, you can configure your own with a connection pool implementation provided by a third party. A popular implementation is R2DBC Pool (r2dbc-pool). Implementations in the Spring distribution are meant only for testing purposes and do not provide pooling.`

cf https://docs.spring.io/spring-framework/reference/data-access/r2dbc.html#r2dbc-ConnectionFactory

You may need to configure the connection pool implementation.

FYI we are using `r2dbc-pool` too: https://github.com/apache/james-project/pull/2190/files

**Comment by elkin5** [comment] 2024-04-19 03:26
> > I really appreciate that you can help me. It is a complex issue and there are few alternatives.
> 
> Are you using r2dbc?
> 
> Recently we have tried a connection pool (instead of a single connection) for our app and the performance is good. The `Cannot exchange messages because the request queue limit is exceeded` seems not to happen anymore.

Yes, i am using r2dbc. How can I configure to have a connections pool  instead of a single connection?

**Comment by elkin5** [comment] 2024-04-19 03:29
Thank you, i will try it
