### ISSUE TITLE
Each time update a draft on Thunderbird, Openpaas creates a new one for the update.

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4329] opened 2021-06-10 02:01 UTC
# Actual Result
Each time updating a draft on Thunderbird, it creates another new draft on OpenPaas.
For example, edit 3 times a draft on Thunderbird, OpenPaas make 3 copies of the draft.

Thunderbird:
![image](https://user-images.githubusercontent.com/69950655/121452588-e4d97c80-c9c9-11eb-9339-6ce1425cc3a2.png)

OpenPaas:
![image](https://user-images.githubusercontent.com/69950655/121452635-fa4ea680-c9c9-11eb-9ec8-2097ef5da068.png)

# Expected result
The draft should be updated on OpenPaas instead of making a new draft.

# Environment
DEV platform
Thunderbird, OpenPaas

**Comment by chibenwa** [comment] 2021-06-10 02:11
Even after ctrl + f5 ?

Is this a new bug? Or can it be reproduced on openpaas.linagora.com?

**Comment by tlle14** [comment] 2021-06-10 02:18
Hi @chibenwa 
1. Even when you refresh the page, the duplicated drafts will not disappear. 
2. This is an old issue but I just have aware of it recently.

**Comment by chibenwa** [comment] 2021-06-10 02:22
Ok. We will  investigate.

@Arsnael is email query view activated on preprod? Can we activate it and re-test?

**Comment by Arsnael** [comment] 2021-06-10 03:04
I will check

**Comment by Arsnael** [comment] 2021-06-10 03:07
@chibenwa It is enabled in the jmap conf, and the corresponding listener is declared too. Bug then?

**Comment by Arsnael** [comment] 2021-06-10 03:08
Ah no wait... @tlle14 is testing on dev not preprod (well because last I know openpaas not really up and running on preprod)

**Comment by Arsnael** [comment] 2021-06-10 03:16
It's present on dev as well... I don't know then

**Comment by chibenwa** [comment] 2021-06-10 03:34
And on openpaas.linagora.com.

I tested with samsung IMAP client, there is only a single email there. Also, ctrl + f5 and the extra mails do not disapear from OpenPaaS.

We likely want to investigate.

**Comment by chibenwa** [comment] 2021-06-11 05:25
I have an idea for this one!

IMAP is based on an expunge model, which means the messages are flagged as `\Deleted` before actually removing messages. The actual deletion requires an EXPUNGE call.

Of course, other IMAP clients do not display `\Deleted` emails while I do think JMAP do!

So the way to fix it could be to have `Email/query` not returning `\Deleted` messages. This could be done:

 - By customizing the search before backend search
 - Maintaining EmailQueryView via the listener to NOT include `\Deleted` messages.

**Comment by chibenwa** [comment] 2021-06-11 05:33
Bingo, confirmed!

Right click on Draft folder + compact does actually do the Expunge, and the extra mails disapear from JMAP.

**Comment by chibenwa** [comment] 2021-06-11 05:43
https://issues.apache.org/jira/browse/JAMES-3597

**Comment by chibenwa** [comment] 2021-06-11 07:33
https://github.com/apache/james-project/pull/490

**Comment by tlle14** [comment] 2021-06-16 03:01
@chibenwa @Arsnael 
The duplicated draft was displaying until I refreshed the page. Do you have any solution to automatically refresh the mailbox?
![Peek 2021-06-16 09-52](https://user-images.githubusercontent.com/69950655/122151219-5cefe880-ce89-11eb-9944-837bc9ec9568.gif)

**Comment by Arsnael** [comment] 2021-06-16 03:09
Can try to check a little but this likely looks like an openpaas issue. I would bet maybe when you click on the little refresh arrow on top it likely just check for new messages, while clicking on the mailbox does a full getMessagesList... 

Will try to confirm that :)

**Comment by chibenwa** [comment] 2021-06-16 03:23
> The duplicated draft was displaying until I refreshed the page. 

Expected. Deletes are not synched by OpenPaaS. If I delete an email in window A, then the email can be seen in window b until I f5.

I close the issue.

**Closed** 2021-06-16 03:23 UTC
Labels: bug, minor
