### ISSUE TITLE
This email doesn't have body when received in James/unifiedInbox

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/james-project#435] opened 2016-10-11 10:13 UTC
Can I haz body ?

[Confirm your email address and register for Jive.eml.txt](https://github.com/linagora/james-project/files/521545/Confirm.your.email.address.and.register.for.Jive.eml.txt)

(renamed to .eml.txt cause github chck for file suffix)

**Comment by aduprat** [comment] 2016-10-11 10:23
The problem is that the text/* parts of this message contains a Content-Disposition (equals to inline); and then are considered as attachments.

**Comment by chibenwa** [comment] 2016-10-11 12:10
It look similar to what we have discussed for the HasAttachment matcher

**Comment by rouazana** [comment] 2016-11-18 09:51
should be fixed: https://issues.apache.org/jira/browse/JAMES-1833

**Closed by rouazana** 2016-11-18 09:51 UTC
