### ISSUE TITLE
Automatically subscribe the user to a folder created with JMAP

### ISSUE THREAD

**Issue by ddolcimascolo** [linagora/james-project#439] opened 2016-10-17 15:07 UTC
Hi guys,

When I create a folder with JMAP I should be immediately subscribed to it. Currently when I browse my account with an IMAP client I don't "see" the folder until I subscribe to it.

Cheers,
David

**Comment by chibenwa** [comment] 2016-11-25 05:53
We are in the corner case of mailbox creation on different connections.

I had a look on RFCs to find something that would notify your IMAP client about mailbox creation (with JMAP). I had a look on : 

 - https://tools.ietf.org/html/rfc3501#section-6.3.3
 - https://tools.ietf.org/html/rfc5465#section-5.4

If you now any RFC for sending mailbox creation notification, and that is also handled by firefox, let me know.

Btw, does closing + opening thunderbird again works ?

**Comment by rouazana** [comment] 2016-11-25 09:22
I think the issue is just that LSUB does not return the folder created in JMAP.

**Comment by chibenwa** [comment] 2017-01-09 08:46
Merged

**Closed** 2017-01-09 08:47 UTC
